/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.oe.gui;

import javase.oe.products.Software;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CC-Student
 */
public class JFrameMuster extends javax.swing.JFrame {

    JInternalFrameSoftware softwareScreen = null;
    JInternalFrameManual manualScreen = null;
    JInternalFrameHardware hardwareScreen = null;

    /**
     * Creates new form JFrameMuster
     */
    public JFrameMuster() {
        initComponents();
        // my code
        setExtendedState(JFrame.MAXIMIZED_BOTH); // to open maxmized
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jDesktopPaneMaster = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUserActions = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuProducts = new javax.swing.JMenu();
        jMenuItemSoftware = new javax.swing.JMenuItem();
        jMenuItemHardware = new javax.swing.JMenuItem();
        jMenuItemManual = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneMasterLayout = new javax.swing.GroupLayout(jDesktopPaneMaster);
        jDesktopPaneMaster.setLayout(jDesktopPaneMasterLayout);
        jDesktopPaneMasterLayout.setHorizontalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jDesktopPaneMasterLayout.setVerticalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jMenuUserActions.setText("User Actions");
        jMenuUserActions.setEnabled(false);

        jMenuItemLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogOut.setText("Log out");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemLogOut);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemExit);

        jMenuBar1.add(jMenuUserActions);

        jMenuProducts.setText("Productss");
        jMenuProducts.setEnabled(false);

        jMenuItemSoftware.setText("Software");
        jMenuItemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSoftwareActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemSoftware);

        jMenuItemHardware.setText("Hardware");
        jMenuItemHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHardwareActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemHardware);

        jMenuItemManual.setText("Manual");
        jMenuItemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManualActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemManual);

        jMenuBar1.add(jMenuProducts);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showLoginScreen();

    }//GEN-LAST:event_formWindowOpened

    public void showLoginScreen() {
        JInternalFrameLogin loginScreen = new JInternalFrameLogin(this);
        loginScreen.setVisible(true);
        jDesktopPaneMaster.add(loginScreen);
        setInternalFrameLocationCenteredLogin(loginScreen);
    }

    private void jMenuItemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSoftwareActionPerformed
        JInternalFrameSoftware softwareScreen = new JInternalFrameSoftware();
        softwareScreen.setVisible(true);
        jDesktopPaneMaster.add(softwareScreen);
        setInternalFrameLocationCenteredSoftware(softwareScreen);

    }//GEN-LAST:event_jMenuItemSoftwareActionPerformed

    private void jMenuItemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManualActionPerformed
        JInternalFrameManual manualScreen = new JInternalFrameManual();
        manualScreen.setVisible(true);
        jDesktopPaneMaster.add(manualScreen);
        setInternalFrameLocationCenteredManual(manualScreen);

    }//GEN-LAST:event_jMenuItemManualActionPerformed

    private void jMenuItemHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHardwareActionPerformed
        JInternalFrameHardware hardwareScreen = new JInternalFrameHardware();
        hardwareScreen.setVisible(true);
        jDesktopPaneMaster.add(hardwareScreen);
        setInternalFrameLocationCenteredHardware(hardwareScreen);

    }//GEN-LAST:event_jMenuItemHardwareActionPerformed


    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        // cofirmation message 
        int option = JOptionPane.showConfirmDialog(null, "Are you sure to logout ?",
                "Logging out ...", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {

            /// show login 
            showLoginScreen();

            // disable menu 
            changeMenuVisibility(false);
            this.jMenuItemSoftware.setVisible(false);
            this.jMenuItemHardware.setVisible(false);
            this.jMenuItemManual.setVisible(false);

        }
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // cofirmation message 
        int option = JOptionPane.showConfirmDialog(null, "Are you sure to Exit ?",
                "Exit app ...", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    public void changeMenuVisibility(boolean action) {
        this.getjMenuUserActions().setEnabled(action);
        this.getjMenuProducts().setEnabled(action);
    }

    public void setInternalFrameLocationCenteredHardware(JInternalFrameHardware jInternalFrameHardware) {

        double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrameHardware.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrameHardware.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrameHardware.setLocation(x, y);
    }

    public void setInternalFrameLocationCenteredManual(JInternalFrameManual jInternalFrameManual) {

        double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrameManual.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrameManual.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrameManual.setLocation(x, y);
    }

    public void setInternalFrameLocationCenteredSoftware(JInternalFrameSoftware jInternalFrameSoftware) {

        double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrameSoftware.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrameSoftware.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrameSoftware.setLocation(x, y);
    }

    public void setInternalFrameLocationCenteredLogin(JInternalFrame jInternalFrame) {

        double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrame.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrame.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrame.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMuster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMuster().setVisible(true);
            }
        });
    }

    public JDesktopPane getjDesktopPaneMaster() {
        return jDesktopPaneMaster;
    }

    public void setjDesktopPaneMaster(JDesktopPane jDesktopPaneMaster) {
        this.jDesktopPaneMaster = jDesktopPaneMaster;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem3() {
        return jMenuItem3;
    }

    public void setjMenuItem3(JMenuItem jMenuItem3) {
        this.jMenuItem3 = jMenuItem3;
    }

    public JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    public void setjMenuItem6(JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    public JMenuItem getjMenuItemExit() {
        return jMenuItemExit;
    }

    public void setjMenuItemExit(JMenuItem jMenuItemExit) {
        this.jMenuItemExit = jMenuItemExit;
    }

    public JMenuItem getjMenuItemHardware() {
        return jMenuItemHardware;
    }

    public void setjMenuItemHardware(JMenuItem jMenuItemHardware) {
        this.jMenuItemHardware = jMenuItemHardware;
    }

    public JMenuItem getjMenuItemLogOut() {
        return jMenuItemLogOut;
    }

    public void setjMenuItemLogOut(JMenuItem jMenuItemLogOut) {
        this.jMenuItemLogOut = jMenuItemLogOut;
    }

    public JMenuItem getjMenuItemManual() {
        return jMenuItemManual;
    }

    public void setjMenuItemManual(JMenuItem jMenuItemManual) {
        this.jMenuItemManual = jMenuItemManual;
    }

    public JMenuItem getjMenuItemSoftware() {
        return jMenuItemSoftware;
    }

    public void setjMenuItemSoftware(JMenuItem jMenuItemSoftware) {
        this.jMenuItemSoftware = jMenuItemSoftware;
    }

    public JMenu getjMenuProducts() {
        return jMenuProducts;
    }

    public void setjMenuProducts(JMenu jMenuProducts) {
        this.jMenuProducts = jMenuProducts;
    }

    public JMenu getjMenuUserActions() {
        return jMenuUserActions;
    }

    public void setjMenuUserActions(JMenu jMenuUserActions) {
        this.jMenuUserActions = jMenuUserActions;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMaster;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHardware;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemManual;
    private javax.swing.JMenuItem jMenuItemSoftware;
    private javax.swing.JMenu jMenuProducts;
    private javax.swing.JMenu jMenuUserActions;
    // End of variables declaration//GEN-END:variables
}
